All: 
	gcc -o gettime gettime.c -g -Wall -Werror
	gcc -o gettimeWithMove gettimeWithMove.c -g -Wall -Werror
	gcc -o rdtscpTest rdtscpTest.c -g -Wall -Werror
	gcc -o rdtscpTestWithMove rdtscpTestWithMove.c -g -Wall -Werror

clean: 
	rm gettime
	rm gettimeWithMove
	rm rdtscpTest
	rm rdtscpTestWithMove
